from app.repositories.google_sheets_repository import GoogleSheetRepository
from app.repositories.google_sheets_repository import TableSheets

#singleton
google_sheet_repository = GoogleSheetRepository()