version: "3.8"

services:
  db:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_USER:  local
      POSTGRES_PASSWORD: local
      POSTGRES_DB:     backend
    command: postgres -c listen_addresses='*'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy

  migrate:
    image: ghcr.io/albardn2/karma-backend:latest-dev
    depends_on:
      - db
    entrypoint: ["alembic", "upgrade", "head"]
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://local:local@db:5432/backend"
    networks:
      - proxy

  web:
    image: ghcr.io/albardn2/karma-backend:latest-dev
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://local:local@db:5432/backend
    networks:
      - proxy

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - webroot:/var/www/certbot:ro                # ACME challenge
      - certs:/etc/letsencrypt:ro                  # your certs
    networks:
      - proxy

  certbot:
    image: certbot/certbot
    # we’ll run this in “docker compose run --rm” mode
    volumes:
      - webroot:/var/www/certbot
      - certs:/etc/letsencrypt
    networks:
      - proxy

volumes:
  postgres_data:
  certs:

networks:
  proxy:
    driver: bridge
