"""add is_deleted to warehouse

Revision ID: 003c09f833a8
Revises: 8a766f87ac3b
Create Date: 2025-04-23 22:11:06.899115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003c09f833a8'
down_revision: Union[str, None] = '8a766f87ac3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse', 'is_deleted')
    # ### end Alembic commands ###
