"""add workflow execution uuid to process

Revision ID: 0597c35f5440
Revises: c4354a8aa6fe
Create Date: 2025-05-30 15:25:19.528983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0597c35f5440'
down_revision: Union[str, None] = 'c4354a8aa6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('workflow_execution_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'process', 'workflow_execution', ['workflow_execution_uuid'], ['uuid'])
    op.alter_column('workflow', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(None, 'process', type_='foreignkey')
    op.drop_column('process', 'workflow_execution_uuid')
    # ### end Alembic commands ###
