"""update credit note and debit note 

Revision ID: 09025bd4aa0a
Revises: 0dc1ae33a742
Create Date: 2025-05-14 10:02:18.496452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09025bd4aa0a'
down_revision: Union[str, None] = '0dc1ae33a742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_note_item', sa.Column('inventory_change', sa.Float(), nullable=True))
    op.add_column('debit_note_item', sa.Column('inventory_change', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debit_note_item', 'inventory_change')
    op.drop_column('credit_note_item', 'inventory_change')
    # ### end Alembic commands ###
