"""update cn and dn

Revision ID: 0dc1ae33a742
Revises: e3d9e7c8f138
Create Date: 2025-05-14 09:54:39.794328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc1ae33a742'
down_revision: Union[str, None] = 'e3d9e7c8f138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_note_item', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.alter_column('credit_note_item', 'customer_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('credit_note_item', 'vendor_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.add_column('debit_note_item', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.alter_column('debit_note_item', 'customer_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('debit_note_item', 'vendor_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debit_note_item', 'vendor_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('debit_note_item', 'customer_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('debit_note_item', 'paid_at')
    op.alter_column('credit_note_item', 'vendor_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('credit_note_item', 'customer_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('credit_note_item', 'paid_at')
    # ### end Alembic commands ###
