"""change employee type to role

Revision ID: 1357fd98fb68
Revises: 853846382ea8
Create Date: 2025-04-20 00:58:10.291727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1357fd98fb68'
down_revision: Union[str, None] = '853846382ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('role', sa.String(length=120), nullable=True))
    op.drop_column('employee', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('type', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('employee', 'role')
    # ### end Alembic commands ###
