"""add is deleted to task

Revision ID: 24ca8cb1d03b
Revises: 3a70fd26b226
Create Date: 2025-05-25 23:32:54.517193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ca8cb1d03b'
down_revision: Union[str, None] = '3a70fd26b226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_deleted')
    # ### end Alembic commands ###
