"""add purchase order item currency

Revision ID: 26098a3af107
Revises: 10e42857853a
Create Date: 2025-04-21 22:50:02.827317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26098a3af107'
down_revision: Union[str, None] = '10e42857853a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_item', sa.Column('currency', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_item', 'currency')
    # ### end Alembic commands ###
