"""add workflow schemas

Revision ID: 26df3499d1a8
Revises: c2020f8e85d1
Create Date: 2025-05-25 16:42:00.645005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26df3499d1a8'
down_revision: Union[str, None] = 'c2020f8e85d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('workflow_uuid', sa.String(length=36), nullable=False),
    sa.Column('parent_task_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('operator', sa.String(length=120), nullable=False),
    sa.Column('task_inputs', sa.JSON(), nullable=True),
    sa.Column('depends_on', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['parent_task_uuid'], ['task.uuid'], ),
    sa.ForeignKeyConstraint(['workflow_uuid'], ['workflow.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('workflow_execution',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('workflow_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['workflow_uuid'], ['workflow.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('task_execution',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('completed_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('task_uuid', sa.String(length=36), nullable=False),
    sa.Column('parent_task_execution_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('depends_on', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['parent_task_execution_uuid'], ['task_execution.uuid'], ),
    sa.ForeignKeyConstraint(['task_uuid'], ['task.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_execution')
    op.drop_table('workflow_execution')
    op.drop_table('task')
    op.drop_table('workflow')
    # ### end Alembic commands ###
