"""remove is filfilled

Revision ID: 2bcae359be27
Revises: ccd581b06886
Create Date: 2025-05-11 15:21:10.143233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bcae359be27'
down_revision: Union[str, None] = 'ccd581b06886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order', 'is_fulfilled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('is_fulfilled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
