"""modify transaction

Revision ID: 2cb0eeae1346
Revises: 469e8da9373b
Create Date: 2025-05-09 00:01:47.797017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb0eeae1346'
down_revision: Union[str, None] = '469e8da9373b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('to_amount', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('to_currency', sa.String(length=120), nullable=True))
    op.alter_column('transaction', 'from_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('transaction', 'from_currency',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'from_currency',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('transaction', 'from_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('transaction', 'to_currency')
    op.drop_column('transaction', 'to_amount')
    # ### end Alembic commands ###
