"""make workflow uuid nullable for task

Revision ID: 319beabc9302
Revises: f9cb35c26985
Create Date: 2025-10-29 05:37:53.163452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '319beabc9302'
down_revision: Union[str, None] = 'f9cb35c26985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('task', 'workflow_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'workflow_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)