"""make cost per unit non nullable, add currency

Revision ID: 34f6bfb6d34f
Revises: 3909b629bdde
Create Date: 2025-04-27 23:01:19.424796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f6bfb6d34f'
down_revision: Union[str, None] = '3909b629bdde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('currency', sa.String(length=120), nullable=False))
    op.alter_column('inventory', 'cost_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'cost_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('inventory', 'currency')
    # ### end Alembic commands ###
