"""add is deleted to inventory event

Revision ID: 361e25030a37
Revises: ba809ee2d901
Create Date: 2025-04-28 21:30:22.981573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361e25030a37'
down_revision: Union[str, None] = 'ba809ee2d901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_event', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_event', 'is_deleted')
    # ### end Alembic commands ###
