"""add trip stop table

Revision ID: 3e3164623832
Revises: ee0b4aedb39f
Create Date: 2025-06-06 14:23:19.811895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3164623832'
down_revision: Union[str, None] = 'ee0b4aedb39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
import geoalchemy2


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_stop',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('trip_uuid', sa.String(length=36), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('customer_uuid', sa.String(length=36), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_uuid'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['customer_uuid'], ['customer.uuid'], ),
    sa.ForeignKeyConstraint(['trip_uuid'], ['trip.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.add_column('customer_order', sa.Column('trip_stop_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'customer_order', 'trip_stop', ['trip_stop_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_order', type_='foreignkey')
    op.drop_column('customer_order', 'trip_stop_uuid')
    op.drop_table('trip_stop')
    # ### end Alembic commands ###
