"""add vehicle status

Revision ID: 3f26d40b0e51
Revises: 7a1346a5b474
Create Date: 2025-06-04 12:17:37.897057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f26d40b0e51'
down_revision: Union[str, None] = '7a1346a5b474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('status', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'status')
    # ### end Alembic commands ###
