"""make exchange rate field explicit

Revision ID: 46c8ddc136bc
Revises: 4b83cd668079
Create Date: 2025-05-08 22:53:45.469743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c8ddc136bc'
down_revision: Union[str, None] = '4b83cd668079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('usd_to_syp_exchange_rate', sa.Float(), nullable=False))
    op.drop_column('transaction', 'exchange_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('exchange_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('transaction', 'usd_to_syp_exchange_rate')
    # ### end Alembic commands ###
