"""modify fixed asset

Revision ID: 4b83cd668079
Revises: 80a6a3f062f3
Create Date: 2025-05-08 13:43:30.666145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b83cd668079'
down_revision: Union[str, None] = '80a6a3f062f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_asset', sa.Column('quantity', sa.Float(), nullable=False))
    op.add_column('fixed_asset', sa.Column('price_per_unit', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_asset', 'price_per_unit')
    op.drop_column('fixed_asset', 'quantity')
    # ### end Alembic commands ###
