"""remove status and paid at for po

Revision ID: 4f1785a6e291
Revises: 95aaeb24c7a9
Create Date: 2025-05-18 18:23:51.640852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f1785a6e291'
down_revision: Union[str, None] = '95aaeb24c7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order', 'status')
    op.drop_column('purchase_order', 'paid_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('purchase_order', sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
