"""change field name to quantity fulfilled

Revision ID: 4f67da36fb14
Revises: 3967d7ac6583
Create Date: 2025-04-26 22:36:53.913549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f67da36fb14'
down_revision: Union[str, None] = '3967d7ac6583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order_item', sa.Column('quantity_fulfilled', sa.Float(), nullable=False))
    op.drop_column('customer_order_item', 'quantity_shipped')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order_item', sa.Column('quantity_shipped', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('customer_order_item', 'quantity_fulfilled')
    # ### end Alembic commands ###
