"""add no sale reason to trip stop

Revision ID: 59a6a58608a1
Revises: f3595f454ea8
Create Date: 2025-06-07 19:46:22.627763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59a6a58608a1'
down_revision: Union[str, None] = 'f3595f454ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_stop', sa.Column('no_sale_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_stop', 'no_sale_reason')
    # ### end Alembic commands ###
