"""add is_deleted field to order items

Revision ID: 5e2b6dc79ec1
Revises: 441fabfd9df3
Create Date: 2025-04-26 22:41:36.311209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2b6dc79ec1'
down_revision: Union[str, None] = '441fabfd9df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order_item', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order_item', 'is_deleted')
    # ### end Alembic commands ###
