"""edit cn

Revision ID: 6116d1be8549
Revises: d72e37f58ebb
Create Date: 2025-05-18 20:29:27.813647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6116d1be8549'
down_revision: Union[str, None] = 'd72e37f58ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_note_item', 'status')
    op.drop_column('credit_note_item', 'paid_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_note_item', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('credit_note_item', sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
