"""modify trip stop

Revision ID: 62046370e87e
Revises: 319beabc9302
Create Date: 2025-10-31 16:20:53.776933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62046370e87e'
down_revision: Union[str, None] = '319beabc9302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_stop', sa.Column('index', sa.Integer(), nullable=True))
    op.add_column('trip_stop', sa.Column('outcome', sa.Text(), nullable=True))
    op.add_column('trip_stop', sa.Column('sales', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('trip_stop', 'no_sale_reason')
    op.drop_column('trip_stop', 'skip_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_stop', sa.Column('skip_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('trip_stop', sa.Column('no_sale_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('trip_stop', 'sales')
    op.drop_column('trip_stop', 'outcome')
    op.drop_column('trip_stop', 'index')