"""update credit note

Revision ID: 63c28be9765c
Revises: 09025bd4aa0a
Create Date: 2025-05-14 11:46:01.822399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c28be9765c'
down_revision: Union[str, None] = '09025bd4aa0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_note_item', 'customer_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('credit_note_item', 'vendor_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('debit_note_item', 'customer_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('debit_note_item', 'vendor_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debit_note_item', 'vendor_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('debit_note_item', 'customer_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('credit_note_item', 'vendor_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('credit_note_item', 'customer_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
