"""make debit note fields nullable

Revision ID: 7012a2ea36ee
Revises: 361e25030a37
Create Date: 2025-04-28 23:31:35.267870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7012a2ea36ee'
down_revision: Union[str, None] = '361e25030a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debit_note_item', 'invoice_item_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('debit_note_item', 'customer_order_item_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('debit_note_item', 'customer_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('debit_note_item', 'vendor_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('debit_note_item', 'purchase_order_item_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debit_note_item', 'purchase_order_item_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('debit_note_item', 'vendor_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('debit_note_item', 'customer_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('debit_note_item', 'customer_order_item_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('debit_note_item', 'invoice_item_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
