"""add affect original field

Revision ID: 76a03280133d
Revises: fc58cdbc7b2e
Create Date: 2025-05-15 23:15:53.763795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a03280133d'
down_revision: Union[str, None] = 'fc58cdbc7b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_event', sa.Column('affect_original', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_event', 'affect_original')
    # ### end Alembic commands ###
