"""add created by

Revision ID: 7f70a2f0fc58
Revises: ec6bd030c832
Create Date: 2025-04-19 18:18:28.161979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f70a2f0fc58'
down_revision: Union[str, None] = 'ec6bd030c832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'batch', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('credit_note_item', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'credit_note_item', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('customer', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'customer', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('customer_order', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'customer_order', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('debit_note_item', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'debit_note_item', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('employee', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'employee', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('expense', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'expense', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('financial_account', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'financial_account', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('fixed_asset', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'fixed_asset', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('inventory', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'inventory', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('inventory_event', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'inventory_event', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('invoice', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'invoice', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('invoice_item', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'invoice_item', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('material', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'material', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('order_item', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'order_item', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('payment', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'payment', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('payout', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'payout', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('pricing', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'pricing', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('purchase_order', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'purchase_order', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('purchase_order_item', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'purchase_order_item', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('transaction', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'transaction', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('vendor', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'vendor', 'user', ['created_by_uuid'], ['uuid'])
    op.add_column('warehouse', sa.Column('created_by_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'warehouse', 'user', ['created_by_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse', type_='foreignkey')
    op.drop_column('warehouse', 'created_by_uuid')
    op.drop_constraint(None, 'vendor', type_='foreignkey')
    op.drop_column('vendor', 'created_by_uuid')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'created_by_uuid')
    op.drop_constraint(None, 'purchase_order_item', type_='foreignkey')
    op.drop_column('purchase_order_item', 'created_by_uuid')
    op.drop_constraint(None, 'purchase_order', type_='foreignkey')
    op.drop_column('purchase_order', 'created_by_uuid')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.drop_column('pricing', 'created_by_uuid')
    op.drop_constraint(None, 'payout', type_='foreignkey')
    op.drop_column('payout', 'created_by_uuid')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'created_by_uuid')
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_column('order_item', 'created_by_uuid')
    op.drop_constraint(None, 'material', type_='foreignkey')
    op.drop_column('material', 'created_by_uuid')
    op.drop_constraint(None, 'invoice_item', type_='foreignkey')
    op.drop_column('invoice_item', 'created_by_uuid')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'created_by_uuid')
    op.drop_constraint(None, 'inventory_event', type_='foreignkey')
    op.drop_column('inventory_event', 'created_by_uuid')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'created_by_uuid')
    op.drop_constraint(None, 'fixed_asset', type_='foreignkey')
    op.drop_column('fixed_asset', 'created_by_uuid')
    op.drop_constraint(None, 'financial_account', type_='foreignkey')
    op.drop_column('financial_account', 'created_by_uuid')
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'created_by_uuid')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'created_by_uuid')
    op.drop_constraint(None, 'debit_note_item', type_='foreignkey')
    op.drop_column('debit_note_item', 'created_by_uuid')
    op.drop_constraint(None, 'customer_order', type_='foreignkey')
    op.drop_column('customer_order', 'created_by_uuid')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'created_by_uuid')
    op.drop_constraint(None, 'credit_note_item', type_='foreignkey')
    op.drop_column('credit_note_item', 'created_by_uuid')
    op.drop_constraint(None, 'batch', type_='foreignkey')
    op.drop_column('batch', 'created_by_uuid')
    # ### end Alembic commands ###
