"""add is deleted to user

Revision ID: 80a6a3f062f3
Revises: 8ea6ffbfd2d7
Create Date: 2025-05-03 11:14:42.387574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a6a3f062f3'
down_revision: Union[str, None] = '8ea6ffbfd2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'language')
    # ### end Alembic commands ###
