"""add is deleted to workflow

Revision ID: 8308110c3f84
Revises: 26df3499d1a8
Create Date: 2025-05-25 21:17:18.751578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8308110c3f84'
down_revision: Union[str, None] = '26df3499d1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'is_deleted')
    # ### end Alembic commands ###
