"""add is deleted field to materisl

Revision ID: 853846382ea8
Revises: 8e88867dcd4c
Create Date: 2025-04-19 20:33:55.594091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853846382ea8'
down_revision: Union[str, None] = '8e88867dcd4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'is_deleted')
    # ### end Alembic commands ###
