"""add is deleted to financial account

Revision ID: 8a766f87ac3b
Revises: 26098a3af107
Create Date: 2025-04-23 03:06:59.006501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a766f87ac3b'
down_revision: Union[str, None] = '26098a3af107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_account', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_account', 'is_deleted')
    # ### end Alembic commands ###
