"""use cached fields 

Revision ID: 8b970d31f21a
Revises: c8dae972e283
Create Date: 2025-05-17 10:57:21.039605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b970d31f21a'
down_revision: Union[str, None] = 'c8dae972e283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('_cached_cost_per_unit', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('_cached_current_quantity', sa.Float(), nullable=True))
    op.add_column('inventory', sa.Column('_cached_original_quantity', sa.Float(), nullable=True))
    op.drop_column('inventory', 'original_quantity')
    op.drop_column('inventory', 'current_quantity')
    op.drop_column('inventory', 'cost_per_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('cost_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('current_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('original_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('inventory', '_cached_original_quantity')
    op.drop_column('inventory', '_cached_current_quantity')
    op.drop_column('inventory', '_cached_cost_per_unit')
    # ### end Alembic commands ###
