"""make transaction account fields nullable

Revision ID: 8ba7c2d705a2
Revises: f893ed5af618
Create Date: 2025-04-26 17:22:46.276529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba7c2d705a2'
down_revision: Union[str, None] = 'f893ed5af618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'from_account_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('transaction', 'to_account_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'to_account_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('transaction', 'from_account_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
