"""materials measure unit

Revision ID: 8e88867dcd4c
Revises: 7f70a2f0fc58
Create Date: 2025-04-19 20:19:44.637313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e88867dcd4c'
down_revision: Union[str, None] = '7f70a2f0fc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('measure_unit', sa.String(length=120), nullable=True))
    op.drop_column('material', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('unit', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('material', 'measure_unit')
    # ### end Alembic commands ###
