"""update process to only use the data field

Revision ID: 8ea6ffbfd2d7
Revises: 9ab137643886
Create Date: 2025-04-29 21:21:39.610352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea6ffbfd2d7'
down_revision: Union[str, None] = '9ab137643886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'cost_per_unit')
    op.drop_column('process', 'unit')
    op.drop_column('process', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('process', sa.Column('unit', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('process', sa.Column('cost_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
