"""add is deleted to debit note item

Revision ID: 92424c2088e2
Revises: 7012a2ea36ee
Create Date: 2025-04-28 23:32:57.717077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92424c2088e2'
down_revision: Union[str, None] = '7012a2ea36ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debit_note_item', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debit_note_item', 'is_deleted')
    # ### end Alembic commands ###
