"""rename transaction fields

Revision ID: 94a8c8559e49
Revises: 46c8ddc136bc
Create Date: 2025-05-08 22:56:29.383948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a8c8559e49'
down_revision: Union[str, None] = '46c8ddc136bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('from_amount', sa.Float(), nullable=False))
    op.add_column('transaction', sa.Column('from_currency', sa.String(length=120), nullable=False))
    op.drop_column('transaction', 'amount')
    op.drop_column('transaction', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('currency', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('transaction', 'from_currency')
    op.drop_column('transaction', 'from_amount')
    # ### end Alembic commands ###
