"""make cost nullable in inventory

Revision ID: 9a515227fbaf
Revises: 2bcae359be27
Create Date: 2025-05-12 23:49:27.453075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a515227fbaf'
down_revision: Union[str, None] = '2bcae359be27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'warehouse_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('inventory', 'cost_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('inventory', 'currency',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'currency',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('inventory', 'cost_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('inventory', 'warehouse_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
