"""update process

Revision ID: 9ab137643886
Revises: c182fe8b3ba2
Create Date: 2025-04-29 21:19:59.561758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab137643886'
down_revision: Union[str, None] = 'c182fe8b3ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('batch_material_uuid_fkey', 'process', type_='foreignkey')
    op.drop_column('process', 'material_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('material_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key('batch_material_uuid_fkey', 'process', 'material', ['material_uuid'], ['uuid'])
    # ### end Alembic commands ###
