"""drop coords for customer and vendor

Revision ID: acfbfa582f93
Revises: 3e3164623832
Create Date: 2025-06-06 17:17:27.861163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfbfa582f93'
down_revision: Union[str, None] = '3e3164623832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'coordinates')
    op.drop_column('vendor', 'coordinates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('coordinates', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('coordinates', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
