"""add is deleted to invoice_item

Revision ID: afcc5c598f7e
Revises: 578a25467c41
Create Date: 2025-04-27 14:00:12.990320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afcc5c598f7e'
down_revision: Union[str, None] = '578a25467c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_item', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_item', 'is_deleted')
    # ### end Alembic commands ###
