"""update expense

Revision ID: bc70094fecb7
Revises: 4f1785a6e291
Create Date: 2025-05-18 18:39:54.907284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc70094fecb7'
down_revision: Union[str, None] = '4f1785a6e291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
