"""add is deleted to credit note item

Revision ID: c182fe8b3ba2
Revises: 92424c2088e2
Create Date: 2025-04-29 20:38:03.021929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c182fe8b3ba2'
down_revision: Union[str, None] = '92424c2088e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_note_item', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('credit_note_item', 'purchase_order_item_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_note_item', 'purchase_order_item_uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('credit_note_item', 'is_deleted')
    # ### end Alembic commands ###
