"""add parameters to workflow definition

Revision ID: c4354a8aa6fe
Revises: e72a02f7927a
Create Date: 2025-05-29 20:20:03.674392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4354a8aa6fe'
down_revision: Union[str, None] = 'e72a02f7927a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('parameters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'parameters')
    # ### end Alembic commands ###
