"""make invoice status hybird

Revision ID: d45227a63110
Revises: 8b970d31f21a
Create Date: 2025-05-18 11:31:16.148579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd45227a63110'
down_revision: Union[str, None] = '8b970d31f21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'status')
    op.drop_column('invoice', 'paid_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('invoice', sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
