"""update dn

Revision ID: d72e37f58ebb
Revises: bc70094fecb7
Create Date: 2025-05-18 19:01:13.314353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd72e37f58ebb'
down_revision: Union[str, None] = 'bc70094fecb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debit_note_item', 'paid_at')
    op.drop_column('debit_note_item', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debit_note_item', sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('debit_note_item', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
