"""update expenses

Revision ID: e3d9e7c8f138
Revises: 9a515227fbaf
Create Date: 2025-05-13 18:29:33.615575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d9e7c8f138'
down_revision: Union[str, None] = '9a515227fbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('status', sa.String(length=120), nullable=False))
    op.alter_column('expense', 'category',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense', 'category',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('expense', 'status')
    # ### end Alembic commands ###
