"""add callback fns

Revision ID: e72a02f7927a
Revises: 1afa84331ed8
Create Date: 2025-05-29 17:03:58.851468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e72a02f7927a'
down_revision: Union[str, None] = '1afa84331ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('callback_fns', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('workflow', sa.Column('callback_fns', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'callback_fns')
    op.drop_column('task', 'callback_fns')
    # ### end Alembic commands ###
