"""update wf models

Revision ID: ebda8f3f5154
Revises: 8308110c3f84
Create Date: 2025-05-25 22:23:11.060889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebda8f3f5154'
down_revision: Union[str, None] = '8308110c3f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_execution', sa.Column('workflow_execution_uuid', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'task_execution', 'workflow_execution', ['workflow_execution_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_execution', type_='foreignkey')
    op.drop_column('task_execution', 'workflow_execution_uuid')
    # ### end Alembic commands ###
