"""add forein key to materials and fixed assets

Revision ID: ec6bd030c832
Revises: cecad43e0fd9
Create Date: 2025-04-19 01:03:39.987352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6bd030c832'
down_revision: Union[str, None] = 'cecad43e0fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_asset', sa.Column('material_uuid', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'fixed_asset', 'material', ['material_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fixed_asset', type_='foreignkey')
    op.drop_column('fixed_asset', 'material_uuid')
    # ### end Alembic commands ###
