"""add rfid token field to user

Revision ID: f098357dfd8f
Revises: 59a6a58608a1
Create Date: 2025-06-08 14:44:41.181994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f098357dfd8f'
down_revision: Union[str, None] = '59a6a58608a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rfid_token', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['rfid_token'])
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'rfid_token')
    # ### end Alembic commands ###
