"""update trip and sa relation

Revision ID: f9cb35c26985
Revises: d643260737c4
Create Date: 2025-10-28 08:06:43.420282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9cb35c26985'
down_revision: Union[str, None] = 'd643260737c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('service_area_names', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_constraint(op.f('trip_service_area_uuid_fkey'), 'trip', type_='foreignkey')
    op.drop_column('trip', 'service_area_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('service_area_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('trip_service_area_uuid_fkey'), 'trip', 'service_area', ['service_area_uuid'], ['uuid'])
    op.drop_column('trip', 'service_area_names')
    # ### end Alembic commands ###
