"""add cost and currency to inventory event

Revision ID: fc58cdbc7b2e
Revises: 2b2bd7c0ae3f
Create Date: 2025-05-15 22:54:36.006679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc58cdbc7b2e'
down_revision: Union[str, None] = '2b2bd7c0ae3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_event', sa.Column('cost_per_unit', sa.Float(), nullable=True))
    op.add_column('inventory_event', sa.Column('currency', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_event', 'currency')
    op.drop_column('inventory_event', 'cost_per_unit')
    # ### end Alembic commands ###
