"""add task execution to trip stop

Revision ID: fc6fa8ebb3e3
Revises: 62046370e87e
Create Date: 2025-10-31 18:05:10.373470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc6fa8ebb3e3'
down_revision: Union[str, None] = '62046370e87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_stop', sa.Column('task_execution_uuid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'trip_stop', 'task_execution', ['task_execution_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip_stop', type_='foreignkey')
    op.drop_column('trip_stop', 'task_execution_uuid')