name: CI – Build Dev Image


permissions:
  contents: read
  packages: write

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Push dev images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1) Grab the first 7 chars of the commit SHA
      - name: Determine short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2) Build & push with two tags
      - name: Build & push images
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/albardn2/karma-backend:latest-dev
            ghcr.io/albardn2/karma-backend:${{ env.SHORT_SHA }}
