name: CD – Migrate Dev DB

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  sync-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Prepare remote directory
        env:
          HOST: ${{ secrets.DEV_DROPLET_HOST }}
          USER: root
          PASS: ${{ secrets.DEV_DROPLET_PASSWORD }}
        run: |
          sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no \
            "$USER@$HOST" "mkdir -p /srv/myapp"

      - name: Rsync docker-compose.yaml
        env:
          HOST: ${{ secrets.DEV_DROPLET_HOST }}
          USER: root
          PASS: ${{ secrets.DEV_DROPLET_PASSWORD }}
        run: |
          sshpass -p "$PASS" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            "$GITHUB_WORKSPACE/backend/docker-compose.yaml" \
            "$USER@$HOST:/srv/myapp/docker-compose.yaml"

  migrate:
    name: Run DB migrations
    needs: sync-compose
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: SSH, login to GHCR & run migrations
        env:
          HOST: ${{ secrets.DEV_DROPLET_HOST }}
          USER: root
          PASS: ${{ secrets.DEV_DROPLET_PASSWORD }}
          GHCR_USER: ${{ github.actor }}
          GHCR_PAT : ${{ secrets.CR_PAT }}
        run: |
          sshpass -p "$PASS" \
            ssh -o StrictHostKeyChecking=no "$USER@$HOST" "\
              # install or ensure Docker is running (skip if you pre-provisioned)
              apt-get update && apt-get install -y curl && \
              curl -fsSL https://get.docker.com | sh && \
              systemctl enable --now docker && \
              # login to GHCR so private images can be pulled
              echo \"\$GHCR_PAT\" | docker login ghcr.io -u \"\$GHCR_USER\" --password-stdin && \
              # go to your app folder and pull + migrate
              cd /srv/myapp && \
              docker compose pull && \
              docker compose run --rm migrate\
          "